version: '3.1'

services:
  frontend:
    container_name: front-end
    build: ./nfc-app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    expose:
      - 3000
    restart: always